import Head from 'next/head'
import Image from 'next/image'
import Main from '../component/Main'
import styles from '../styles/Home.module.css'

export default function Home({ data,data2}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Main data={ data } data2={ data2 }/>

</>
     
 
  )
}


export async function getStaticProps(context) {
	const res = await fetch(`https://api.ipify.org/?format=json`);
	const data = await res.json();
	const res2 = await fetch(
		`http://universities.hipolabs.com/search?country=oman`,
	);
	const data2 = await res2.json();

	if (!data) {
		return {
			notFound: true,
		};
	}

	return {
		props: { data,data2 }, // will be passed to the page component as props
	};
}